version: '3.7'

services:
  backend:
    image: backend:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=viaduct.proxy.rlwy.net
      - DATABASE_USER=root
      - DATABASE_PASSWORD=nTCVOGWadvcBeXngVHaxsnZkgpBHhERn
      - DATABASE_NAME=railway

  frontend:
    image: frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

